import defaultTheme from 'tailwindcss/defaultTheme';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e5e2e1',
        'surface-container-low': '#291715',
        primary: '#ffb4aa',
        'surface-container-high': '#392522',
        'on-secondary': '#313030',
        'primary-container': '#ff5545',
        'on-primary-fixed': '#410001',
        'on-surface-variant': '#e7bdb7',
        background: '#1f0f0d',
        'on-primary-container': '#5c0002',
        'on-primary': '#690003',
        'on-background': '#fcdbd6',
        'surface-container-lowest': '#190a08',
        'on-tertiary-fixed-variant': '#46464b',
        'surface-tint': '#ffb4aa',
        outline: '#ad8883',
        'primary-fixed': '#ffdad5',
        'on-secondary-fixed': '#1c1b1b',
        'on-surface': '#fcdbd6',
        'surface-container': '#2d1b18',
        'surface-container-highest': '#44302d',
        'primary-fixed-dim': '#ffb4aa',
        'secondary-fixed-dim': '#c9c6c5',
        tertiary: '#c6c6cb',
        'on-error': '#690005',
        'inverse-on-surface': '#402b29',
        'surface-variant': '#44302d',
        'on-error-container': '#ffdad6',
        secondary: '#c9c6c5',
        surface: '#1f0f0d',
        'inverse-surface': '#fcdbd6',
        'surface-bright': '#493431',
        error: '#ffb4ab',
        'on-tertiary': '#2f3034',
        'on-tertiary-fixed': '#1a1b1f',
        'surface-dim': '#1f0f0d',
        'tertiary-container': '#909095',
        'secondary-container': '#4a4949',
        'tertiary-fixed-dim': '#c6c6cb',
        'outline-variant': '#5d3f3b',
        'on-tertiary-container': '#282a2e',
        'on-primary-fixed-variant': '#930005',
        'on-secondary-fixed-variant': '#474646',
        'inverse-primary': '#c0000a',
        'error-container': '#93000a',
        'on-secondary-container': '#bab8b7',
        'tertiary-fixed': '#e3e2e7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        'container-max': '1200px',
        gutter: '24px',
        unit: '8px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-md': ['JetBrains Mono', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'code-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        display: ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
