import defaultTheme from 'tailwindcss/defaultTheme';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#9aa8b7',
        'surface-container-low': '#121a24',
        primary: '#66d9ff',
        'surface-container-high': '#1f2f3f',
        'on-secondary': '#d8e3f1',
        'primary-container': '#1f82b5',
        'on-primary-fixed': '#071c26',
        'on-surface-variant': '#9fb8d0',
        background: '#101721',
        'on-primary-container': '#eef9ff',
        'on-primary': '#e6f9ff',
        'on-background': '#e8edf2',
        'surface-container-lowest': '#0c131a',
        'on-tertiary-fixed-variant': '#5f6f83',
        'surface-tint': '#68dafe',
        outline: '#31516d',
        'primary-fixed': '#b3f2ff',
        'on-secondary-fixed': '#1b242e',
        'on-surface': '#dce6ef',
        'surface-container': '#16202b',
        'surface-container-highest': '#28394a',
        'primary-fixed-dim': '#9ce4ff',
        'secondary-fixed-dim': '#b8cad8',
        tertiary: '#b4c5d8',
        'on-error': '#7d131d',
        'inverse-on-surface': '#1e2933',
        'surface-variant': '#243240',
        'on-error-container': '#ffdad6',
        secondary: '#8ea8c3',
        surface: '#101721',
        'inverse-surface': '#f7fbff',
        'surface-bright': '#25354a',
        error: '#ff8fa2',
        'on-tertiary': '#2b3747',
        'on-tertiary-fixed': '#161e2b',
        'surface-dim': '#101721',
        'tertiary-container': '#4c6a86',
        'secondary-container': '#2f4a65',
        'tertiary-fixed-dim': '#cfd8e7',
        'outline-variant': '#3d5b75',
        'on-tertiary-container': '#18202c',
        'on-primary-fixed-variant': '#5b8ab7',
        'on-secondary-fixed-variant': '#4f6071',
        'inverse-primary': '#a2ebff',
        'error-container': '#a01f30',
        'on-secondary-container': '#c2d2e3',
        'tertiary-fixed': '#dbe6f1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        'container-max': '1200px',
        gutter: '24px',
        unit: '8px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-md': ['JetBrains Mono', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'code-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        display: ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
